### ISSUE TITLE
HSL free builds on github actions

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-ext#147]
Look into building without the HSL on github actions.

**Comment by ksbeattie** [comment]
Part of https://github.com/IDAES/idaes-pse/issues/157  Though if we can get this for other platforms, we should.

**Comment by andrewlee94** [comment]
@eslickj Do we still want/need to do this?

**Comment by eslickj** [comment]
Probably don't need it.  I did this for macOS.  If anyone has a good reason to do this on other operating systems, they can open a new issue.
