### ISSUE TITLE
Supported linux versions?

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-ext#17]
Now that we have docker containers to do the Linux and Windows builds, we need to decide what versions of Linux to build on, what versions of Linux to test on, and how to select a build to get.

So far, I think the only real issue we've had is libgfortran version.  There could be an issue with the Lapack and Blas versions, but they may be tied to the fortran version.

For testing, I guess we just select a set of Linux distros and version to support and test them.  For builds, maybe we can just do CentOS7 and CentOS8, then hopefully we could classify the distros we support into selecting one of those.   Alternatively we could do a build for every distro we decide to support and let the user choose the best match if they have an unsupported distro.

I think we'd be pretty safe getting the distro and version from /etc/os-release.

**Comment by eslickj** [comment]
For CentOS7 the gfortran version is weirdly confusing.

```
[root@98709d138d5d /]# yum list installed | grep libgfortran
libgfortran.x86_64                        4.8.5-39.el7                  @base
[root@98709d138d5d /]# ldconfig -p | grep libgfortran
        libgfortran.so.3 (libc6,x86-64) => /lib64/libgfortran.so.3
```

**Comment by jsiirola** [comment]
Personally, I would advocate building on the oldest platforms possible.  At least for the machines I deal with there are still a number of RHEL6 boxes around, so *my* life would be easier if we supported back to RHEL6 (CentOS6).

**Comment by eslickj** [comment]
I had some problem with CentOS6, but I didn't try hard because it's pretty close to being unmaintained.  Since the docker stuff is so much easier, I give it a shot.

**Comment by eslickj** [comment]
I'm building on CentOS 6 now and I see the issue is no C++11.  I'll let Ipopt finish and see what I can do.  I think I required it for some memoization stuff in the property libraries.  I don't remember the details, but I don't think it was especially easy to lose the dependency.

**Comment by eslickj** [comment]
I should add Ipopt compiled successfully so the CentOS 6 issue is only property libraries.

**Comment by eslickj** [comment]
Okay, I remove the (apparently no longer needed) stdc++11 flag and CentOS6 build is apparently working.  I don't know why C++ 11 was required, but whatever the reason I must have done away with it at some point.

**Comment by eslickj** [comment]
I guess this is pretty complicated.  I built and tested CentOS 6, 7, and 8.  I'm working my way thorough Ubuntu 18.04, 19.10 and 20.04.  I think detecting and deciding which version to to use is going to be crazy complex, so I'm just going to add an option to get extensions called ```--os <build plaform>``` in {windows, darwin, linux, centos6, centos7, centos8, ubuntu1804, ubuntu1910, ubuntu2004}.  We can add distros if necessary, but this should cover everyone.  So two things

1.)  Do we want to force Linux users for select one?
2.)  If not what should we default to?  Like I said, auto detecting the distro is possible, but I don't want to go there right now.  Mostly these should probably all work on whatever, but it seems that some older library versions like gfortran3 are no longer easily available on newer distros.  So it's probably easier to have specific builds and specific instructions.

**Comment by eslickj** [comment]
Ok, I guess this is decided.  I think we have enough builds to keep most people happy.  If someone complains I can add more.  Unspecified linux maps to centos7, just because that's what we had before.  If someone needs something different they will have to specify with a command line option.  see https://github.com/IDAES/idaes-dev/pull/788

**Comment by ksbeattie** [comment]
@eslickj, though this is a close issue now, I think/hope that we should be able to add to our test harness (via CircleCI + docker containers or in Jenkins with VMs or containers), a set of tests to run these builds.  So that we can be alerted to when something breaks in an old dist that none of us use on a regular basis.

**Comment by eslickj** [comment]
@ksbeattie I have a bunch of test dockerfiles.  They'll need a little work, but we should be close to being able to setup automated testing for all these.
