### ISSUE TITLE
Distribute /include as part of solvers

### ISSUE THREAD

**Issue by jsiirola** [IDAES/idaes-ext#204]
Can we update the idaes-ext to also distribute the `/include` directory from the solver builds (in particular for the COIN solvers)?  I am trying to build other things (SCIP) against the idaes-ext distribution, and not having the includes is breaking the build.

This may cause us to re-think the tarballs that we distribute...?

**Comment by eslickj** [comment]
@jsiirola, As far as I know we only include AMPL executable versions of the COIN solvers, except for Ipopt where we also include a shared library version.  I only build static libraries for everything else, and don't distribute them.  Do you just need the Ipopt headers?

I install the COIN solvers to their own directory when building them. Then I copy the executables from there to make the binary distribution.  That means I have the /include, /libs, and /lib64 directories, I could easily include them, but we'd need to sort out the HSL.

**Comment by eslickj** [comment]
Headers are no problem.  I'll just kick out the HSL headers.  I don't distribute the static libraries because I don't really know which ones link the HSL (so if used would result in a linking error).  I didn't really see the non-ipopt headers as useful, but I may be wrong.

I will include them in the next release.  The best way for a person to use them is another matter.  I can put an "include" directory in the IDAES directory.

**Comment by jsiirola** [comment]
An /include would certainly be good.  We might consider a longer-term solution of restructuring the `~/.idaes` directory to have a "closer to sttandard" layout, with `/bin`, `/lib`, `/include`, and `/share`.  Windows is a bit of a question, though - because it doesn't really support `LD_LIBRARY_PATH`.  Maybe architecture-specific?

**Comment by eslickj** [comment]
@jsiirola, I for sure could do that and make it arch specific.  I'd just have bin be both lib and bin on Windows and the proper structure on Linux and macOS.  I guess I can include the libraries too and kick out the HSL library.  Sure sometimes you may need to provide the HSL yourself depending on what you want to do, but it could still be pretty useful.

I'm working on a new version of the Helmholtz EoS functions, so I'll have to make a new release hopefully in the next month or so.

**Comment by eslickj** [comment]
They are now in the solvers package in another tar.gz file.  Now the issue of updating the install methods can go the ideas-pse repo.  This is done with the 3.0.0 release
