### ISSUE TITLE
How to get idaes extensions for Ubuntu 16.04?

### ISSUE THREAD

**Issue by ZedongPeng** [IDAES/idaes-ext#205]
`idaes get-extensions` only supports Ubuntu 18.04 and above.
How can I get idaes extensions for Ubuntu 16.04?

**Comment by ksbeattie** [comment]
@ZedongPeng, unfortunately the oldest release of Ubuntu we build binaries for is Ubuntu 18.

There are some pointers to instructions on how to build them yourself under the [doc/build.md](../blob/main/doc/build.md) file.

**Comment by ksbeattie** [comment]
Closing this for now, though am interested if you got it working.
