### ISSUE TITLE
Windows tar.gz bundles ipopt dependencies in idaes-lib

### ISSUE THREAD

**Issue by jsiirola** [IDAES/idaes-ext#25]
In the Windows tarball, the ipopt dependencies (`libblas.dll`, `libstcc++.dll`, `libquadmath-0.dll`, `libgfortran-4.dll`, `liblapack.dll`) are bundled in the `idaes-lib-windows-64.tar.gz` file and not in the `idaes-solvers-windows-64.tar.gz`.  This forces windows users who want to run ipopt to download both .tar.gz files.  In addition, the `license.txt` indicates that those DLLs should be in the `*-solvers-*` file.

**Comment by eslickj** [comment]
Yeah, the way they are split was because the libs file goes to idaes\lib and the solvers file goes to ideas\bin.  They should be bundled the way you suggest, but I need to rework how I unpack.

I probably should just put a bin and lib directory in both the tars.

**Comment by eslickj** [comment]
Fixed in PR #26
