### ISSUE TITLE
idaes-solvers-ubuntu2004-64.tar.gz is missing ipopt

### ISSUE THREAD

**Issue by ksbeattie** [IDAES/idaes-ext#38]
It appears that `idaes-solvers-ubuntu2004-64.tar.gz` is missing the actual `ipopt` binary.

**Comment by eslickj** [comment]
Built a new one, and I'm testing it now.

**Comment by eslickj** [comment]
Okay, I built a new one and tested it against Idaes-pse.  Should be good to go.  Do you want me to just update the broken one, or should we create a new release?
[idaes-solvers-ubuntu2004-64.tar.gz](https://github.com/IDAES/idaes-ext/files/4973690/idaes-solvers-ubuntu2004-64.tar.gz)
[idaes-lib-ubuntu2004-64.tar.gz](https://github.com/IDAES/idaes-ext/files/4973692/idaes-lib-ubuntu2004-64.tar.gz)

**Comment by ksbeattie** [comment]
It really depends on the amount of effort to cut a new release.  It would be nice to have a "clean" 2.1.1 with the correct version number in there (without the "dev1").  Maybe it's just me being too picky, but that kinda bugs me.

If it's just a matter of re-rolling the .tar.gz files with the fixed license.txt files, I'll help out with that.

**Comment by eslickj** [comment]
Oh, yeah.  Didn't even think about the version number.  Updating the version that is reported is a matter of editing the version.txt file in the tarballs.  If you want to do that, that's okay with me.  I don't want to do anything by hand like that.  100% chance I'll mess it up.  I guess I could also just rebuild and retest everything.  May not be a bad idea, since apparently I missed the fact that ipopt was missing in one of builds.

If we do do a new version, we also need to remember to update the default download URL in idaes's config.py.

**Comment by ksbeattie** [comment]
I can do the by hand stuff if needed, is the rebuilding/testing automated?  If so, that's perhaps the way to go.

Is it also the case that a new release of idaes-ext can't really be effective (used by default by `idaes get-extensions`) unless a new release of idaes-pse is done (with an updated `config.py`)?  If so, that's unfortunate and we should probably look into using the same mechanism that get-examples uses - that it grabs a mapping file from master (on examples-pse) that we can updated when either is upgraded.

**Comment by eslickj** [comment]
Yeah, the build and test is automated.  I have docker set up to do it.  It's a bit time consuming, but I just have to kick-off the builds and hope for the best.

**Comment by eslickj** [comment]
@jsiirola, the builds pull the latest pynumero master, I just realized I need to make sure I test that.  Anyway I guess the will get us the latest Pynumero library.  Hope it doesn't break anything, but I'll find out.

**Comment by eslickj** [comment]
Okay, the newest pynumero library passes the tests.  I'll go ahead and update the version number, rebuild, and retest everything.

**Comment by eslickj** [comment]
Alright new release is tested, and working. https://github.com/IDAES/idaes-ext/releases/tag/2.1.1
