### ISSUE TITLE
Add k_aug binary

### ISSUE THREAD

**Issue by adowling2** [IDAES/idaes-ext#49]
@adowling2 has recent experience compiling on macOS. This will be needed to use the upcoming sensitivity toolbox.

**Comment by eslickj** [comment]
@adowling2, I probably should know this, but can you point me to the K_aug code and docs?

**Comment by adowling2** [comment]
https://github.com/dthierry/k_aug

@JanghoPark-LBL and I have limited experience getting it to compile.

Based on the limited documentation, I am worried that k_aug assumes the user has the HSL library installed (and in path). But my understanding is that we are distributing a version of Ipopt is compiled with Ipopt but does NOT expose the HSL to calls from other functions. (Ipopt allows you to either compile HSL as part of Ipopt or load it as a library.) @jsiirola knows more about this than me.

**Comment by eslickj** [comment]
Scripts are updated, and the binaries are built and in the test release now.  Once I get them tested I'll make an official 2.2.0 binary release, we can bump the binary release version with the main IDAES release.

**Comment by eslickj** [comment]
Okay it should be done.  We'll need to do some testing.  We don't have tests for k_aug, but the rest is good.
