### ISSUE TITLE
Lapack dependency for HSL

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-ext#5]
Currently the compile\_solvers script ends in HSL configure not finding Lapack, unless you use the system Lapack.  I added a issue for the coinbrew script here:  https://github.com/coin-or/coinbrew/issues/24.

**Comment by eslickj** [comment]
@jsiirola, can one of you guys create a new IDAES branch on our Ipopt fork?  Now that the coinbrew script is working for us, I think we are free to move on to a newer version.  I guess the problem with dependency order may have been our old version.  I'm having trouble tracking exactly when this Dependency file comes into existence and how it evolves but I guess it it is the source of this problem.  See here 

https://github.com/coin-or/coinbrew/issues/24

If we have trouble with the newest version, I assume we can just edit the file on our fork, and make it work.

**Comment by jsiirola** [comment]
@eslickj: I just added IDAES/core-dev with write acces to the fork, so I don't need to be on the critical path.

**Comment by eslickj** [comment]
Ah dang, I liked having you do everything.

**Comment by eslickj** [comment]
Thought these would https://github.com/IDAES/Ipopt/pull/1 and https://github.com/IDAES/idaes-ext/pull/6.  Lapack is built before HSL now and the libraries are there where they are supposed to be, just not found by the configure script for HSL.  I'm not sure what's wrong, but I assume there is a bit of an oversite in some build script somewhere (not mine).

@ksbeattie, @carldlaird, @jsiirola, and @andrewlee94, do you guys have any objection to just using system shared libraries for blas and lapack on Linux.  It should be better and most people should have them or can install them easy enough.  On windows, we can just distribute them like we do with a few other MinGW runtime things.

**Comment by carldlaird** [comment]
The shared system libraries are often (significantly) faster. IPOPT supports both for convenience.

**Comment by ksbeattie** [comment]
Perhaps some kind of "pre-flight" check within get-extensions is possible to print a nicely formatted error so the user is notified in a clear way.

**Comment by jsiirola** [comment]
I am fine with using the system libraries.  That said, I have been burned in the past by other packages that had "implicit" dependencies on the system blas/lapack (numpy).  The problem was that code that attempted to load the library was sufficiently removed from the user that the link error was suppressed and converted into something like an import error.  There were several occasions when I was moving to a new machine where I pulled my hair out tracking down "why doesn't this import?!? it's right there!"

(I should note that while blas/lapack are trivial to install for Linux, they are *not* installed by default on most "general user" systems.)

For the case of ipopt (because invocations will be separated from the user by the Pyomo solver interface), I think it would be very valuable to add some extra error trapping to the Pyomo ipopt interface to explicitly look for the link error and produce a more user-parsable error.

**Comment by eslickj** [comment]
Yeah, I'm thinking of adding ```find_library("lapack")``` or some such to check.  It's probably not air tight.  We could also maybe do an Ipopt test run where we are better equipped to catch and report errors.  I'll try to figure something out.

**Comment by jsiirola** [comment]
@eslickj: wouldn't it be sufficient to just make this "Pyomo's problem" and defer the check / error message to the `solve()` that actually tries to use ipopt?  A user that was going to just use conopt for everything shouldn't have to care about the lapack library...

**Comment by eslickj** [comment]
@jsiirola, heck yeah, that'd be awesome.  I was afraid to ask.  I guess we still bear some responsibility in IDAES, since we're providing the Ipopt binary.

**Comment by carldlaird** [comment]
@eslickj I am confused. Aren't these scripts for *our* compiling of the binaries that are distributed with IDAES? If so, shouldn't we be making sure everything is going to work? 

If so, I think we should error on the side of reliability and make sure we compile in the appropriate pieces (LAPACK, BLAS, etc).

Am I misunderstanding?

**Comment by eslickj** [comment]
@carldlaird you understand right.  I was compiling in Lapack and Blas, using the Thirdparty downloads.  With the new coinbrew system, I can't get HSL to pick up the "Thirdpary" Lapack.  Shared Lapack works, so now I'm trying to make things easy for myself, by not attempting to statically link the Thirdparty Lapack and Blas.

Basically, I'm trying to get away with being lazy.

**Comment by eslickj** [comment]
Well, I tried harder and changed the Thirdparty build harness versions to older versions.  HSL compiled fine, but then it was IPOPT that couldn't find Lapack.  I'm starting to think the new configure scripts don't look for libcoinlapack.

**Comment by eslickj** [comment]
Alright could be this
```
configure: WARNING: unrecognized options: --with-coin-instdir
```

**Comment by eslickj** [comment]
Okay, I'm going to say there is definitely something about the new configure scripts that breaks the ThridParty Blas and Lapack.    The whole coinbrew build script thing, makes it sufficiently opaque to me, that I'm going to give up and dynamically link blas and lapack.  If someone else wants to fix this that cool, but I'm not going to spend more time on it.

We may have to temporarily give up on static linking those, but we can build the latest ipopt and the rest of the CoinOR stuff.  Also I think most people use windows, and there we can just include the DLLs. On Linux, we already have this issue with libgfortran, so installing a couple more libraries while their at it shouldn't be a big deal.

**Comment by eslickj** [comment]
Okay, I'm not going to attempt to statically link blas and lapack anymore, so I'll just close this.  I think we'll start doing the linux build for additional platforms, so we should be able to cover various version and on windows we just include the libraries in the distribution.

**Comment by adowling2** [comment]
@nicolepcortes is having issues with this when running `idaes get-extensions` on our cluster.

**Comment by eslickj** [comment]
@adowling2, probably to be expected.  What's the problem?  Which version of Linux?  I assume since this popped up here it's a Blas/Lapack issue.
