### ISSUE TITLE
Improve get-extensions download error reporting

### ISSUE THREAD

**Issue by ksbeattie** [IDAES/idaes-ext#61]
A user is trying to get extensions on what appears to be a 32 bit version of Windows:

![image](https://user-images.githubusercontent.com/1534843/95931137-353a0500-0d7d-11eb-86b6-5562b846dcc9.png)

Two ideas:

 - [ ] Build windows 32 bit versions of the extensions
 - [ ] Improve the error reporting when the extensions attempting to be download is not there.

**Comment by jsiirola** [comment]
Is the user actually running 32-bit windows, or do they just have a 32-bit version of python installed?

**Comment by eslickj** [comment]
@jsiirola, that's a good question.  It shouldn't matter if they have 32 bit Python, but I get that information from Pyomo's get_os_version() function, so I assumed 32 bit Windows.  I can pretty easily add a better warning.  I don't really want to add anything to my list of stuff to compile if I can help it, but it shouldn't be too hard to compile 32 bit versions. I was hoping this would never happen.

**Comment by jsiirola** [comment]
@eslickj `FileDownloader.get_os_version()` doesn't return the bit size; that comes from `FileDownloader.get_sysinfo()`.  `get_sysinfo()` returns 32 / 64 based on `sys.maxsize`, which is an indication of how *python* was compiled (and not necessarily what the underlying OS is capable).

I definitely agree, though: we should *not* get into the business of building 32-bit binaries.

**Comment by ksbeattie** [comment]
I asked the user to check if they might have installed the 32-bit version of Anaconda on a 64-bit version of Windows - which I think would explain this situation.  We might think about updating the docs about which version of Anaconda to install.

**Comment by eslickj** [comment]
32-bit python should be fine (I think), I need to check that we are getting the os bits correctly.  If I'm getting the Python build bits instead of OS bits it should be an easy fix.  I'll check on that as soon as I get a chance.

**Comment by jsiirola** [comment]
The problem is that I am pretty sure that the bit-ness of a DLL has to match whatever application is opening it.  That is, I am pretty sure that if a 32-bit python attempts to load a 64-bit DLL you will get problems.  This is an issue for compiled external functions that have to be loaded into both Python (for evaluation / initialization) and into the solvers (like ASL/ipopt).  I am pretty sure we will hit issues if everything doesn't match.

...in other words, I think we should *only* support 64-bit environments (unless someone is willing to explicitly pay for 32-bit support)

**Comment by eslickj** [comment]
@jsiirola, I see.  Yeah you are right about that.  I was thinking of running Ipopt as a separate process, but I forgot that Pyomo needs to call those external functions too.  Then there is also Pynumero.

So the solution is may sure we specify 64 bit Python in the install instructions and add better error output here.

**Comment by jsiirola** [comment]
@eslickj: yes.  That would certainly be my recommendation.

**Comment by ksbeattie** [comment]
Update: the user was indeed running a 64bit Windows but was somehow running 32bit python (perhaps by installing the 32bit Anaconda by mistake, I think).  He's re-installed things (probably Anaconda itself) and the get-extensions is working for him now.

So, I'm going to rename/recast this issue to just improve the error reporting when a download fails.

**Comment by ksbeattie** [comment]
I believe this was fixed (somewhat unintentionally) in IDAES/idaes-dev#1235
