### ISSUE TITLE
Rebuild for k_aug typo, and cut 2.4.1 release

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-ext#84]
Need to rebuild and do 2.4.1 release to pick up https://github.com/dthierry/k_aug/commit/2c3f95323760e01f190df4b3ed7a04e8010a6bab.

**Comment by adowling2** [comment]
@eslickj Was this done? Once your code is in main, I'm going to merge main into my macOS branch for additional testing. @jialuw96

**Comment by eslickj** [comment]
@adowling2, I'm testing the new set of binaries now.  Should be up in an hour or so.  The scripts to build things are most likely fine in main, if you want to start.  I added new solvers recently, so there may be a lot of changes.  On the plus side I bypassed the coinbrew script, so you have more direct control.  I suspect that will make things easier on Mac.

**Comment by eslickj** [comment]
Release 2.4.1 is out and apparently working.
